### ISSUE TITLE
Feature request: Locks

### ISSUE THREAD

**Issue by phellarv** [mgejke/hass-sectoralarm#6]
I have a Yale Doorman which is integrated into the alarm system. It would be very nice to control this. I can beta-test if you want to.

**Comment by mgejke** [comment]
I can try to take a look, but I might need some help to understand how it works...

**Comment by phellarv** [comment]
Here is a python library with functional lock control: https://github.com/petterl/python-sectoralarm

**Comment by phellarv** [comment]
Had the time to have a look at it?

**Comment by bokaking** [comment]
It wold be great if you can take a look on locks. Lot of people would appreciate this feature.

**Comment by mgejke** [comment]
Yeah, sorry, I forgot to answer. I did have a short look, but the other project uses a different set of urls than I do so it wasn't as straightforward as I hoped. 

If any of you could find the endpoints and payloads that the web-ui uses, that would help:
https://mypagesapi.sectoralarm.net/

**Comment by marcusramberg** [comment]
``` 
GET https://mypagesapi.sectoralarm.net/Locks/GetLocks/?WithStatus=true&id=<redacted>

response
[{
    "Label": null,
    "PanelId": "redacted",
    "Serial": "redacted",
    "Status": "unlock",
    "SoundLevel": 0,
    "AutoLockEnabled": false,
    "Languages": null
}, {
    "Label": null,
    "PanelId": "redacted",
    "Serial": "redacted",
    "Status": "lock",
    "SoundLevel": 0,
    "AutoLockEnabled": false,
    "Languages": null
}]



POST  https://mypagesapi.sectoralarm.net/Locks/Lock
{"id":"redacted","LockSerial":"redacted","DisarmCode":"redacted"}

response:
{
    "panelData": null,
    "Message": null,
    "Status": "success"
}
```

**Comment by mgejke** [comment]
@marcusramberg Awesome!

I've made an initial test:
Clone the branch **locks** from this repo
Clone the branch **locks** from https://github.com/mgejke/asyncsector and put in in your `<config_folder>\deps\PythonXX\site-packages\asyncsector\`

Hopefully fetching the state of the locks should work... It that seems ok, I'll try to get locking/unlocking working as well!

**Comment by marcusramberg** [comment]
After loading those I get ```
2018-12-03 11:40:38 ERROR (MainThread) [homeassistant.loader] Unable to find component lock.sector_alarm
2018-12-03 11:40:38 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform lock.sector_alarm: Platform not found.
```

**Comment by mgejke** [comment]
I seem till have missed a folder when committing, will fix tonight...

**Comment by mgejke** [comment]
Fixed!

**Comment by marcusramberg** [comment]
Awesome. This works 🎉 I now have two locked locks in state list :)

**Comment by marcusramberg** [comment]
Also trying to unlock triggers the NotImplementedError stubs as expected. 💯

**Comment by phellarv** [comment]
Every second time I restart hassio, the component consistently fails with a timeout-error (branch: Locks):

2018-12-04 17:41:49 ERROR (MainThread) [homeassistant.setup] Error during setup of component sector_alarm
Traceback (most recent call last):
  File "/config/deps/lib/python3.6/site-packages/asyncsector/asyncsector.py", line 37, in login
    AsyncSector.Base + AsyncSector.Login, json=self._auth)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 391, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 757, in start
    message, payload = await self._protocol.read()
  File "/usr/local/lib/python3.6/site-packages/aiohttp/streams.py", line 543, in read
    await self._waiter
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/setup.py", line 145, in _async_setup_component
    hass, processed_config)
  File "/config/custom_components/sector_alarm.py", line 60, in async_setup
    if not await async_sector.login():
  File "/config/deps/lib/python3.6/site-packages/asyncsector/asyncsector.py", line 43, in login
    return True
  File "/usr/local/lib/python3.6/site-packages/async_timeout/__init__.py", line 45, in __exit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.6/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError

**Comment by phellarv** [comment]
But the other times it works like a charm.

**Comment by mgejke** [comment]
@phellarv That seems to be related to the login, strange.

**Comment by mgejke** [comment]
Pushed some new code that perhaps makes it possible to lock/unlock. Please try it out!

@marcusramberg The post command you posted only has a `Locks/Lock` endpoint, and there's nothing in the payload to indicate unlock/lock, so for this iteration I just implemented it as a toggle...

**Comment by marcusramberg** [comment]
@mgejke I don't see the new code. perhaps you forgot to push? The endpoint for unlock is Locks/Unlock btw.

**Comment by mgejke** [comment]
Odd. I'm pretty sure I pushed, and the latest command left in the console was push... 

It's pushed now anyway, with the added Unlock endpoint.

**Comment by phellarv** [comment]
2018-12-12 00:40:35 ERROR (MainThread) [homeassistant.components.lock] Error while setting up platform sector_alarm
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/config/custom_components/lock/sector_alarm.py", line 22, in async_setup_platform
    code = discovery_info[sector_alarm.CONF_CODE]
KeyError: 'code'

**Comment by mgejke** [comment]
@phellarv Fixed, I think...

**Comment by phellarv** [comment]
Yes - No errors now. But locking and unlocking does not do anything. And there is no error message. Anything I can do to debug this?

**Comment by marcusramberg** [comment]
Same for me fwiw

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by marcusramberg** [comment]
Is there an ENV variable or something to set to dump the http request being made for debugging?

**Comment by Lintan83** [comment]
How is it going with the locks or how can i get them integrated to my hass.io?

**Comment by phellarv** [comment]
Is this branch dead?
